#nullable enable
using System.Security.Claims;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace PutZige.API.Tests.Integration;

public class TestAuthHandler : AuthenticationHandler<AuthenticationSchemeOptions>
{
    public TestAuthHandler(IOptionsMonitor<AuthenticationSchemeOptions> options, ILoggerFactory logger, UrlEncoder encoder, ISystemClock clock)
        : base(options, logger, encoder, clock) { }

    protected override Task<AuthenticateResult> HandleAuthenticateAsync()
    {
        // Accept tokens generated by the CreateUserAndLoginAsync helper (JWT) or tokens of form "Test {guid}" where guid maps to user id.
        var auth = Request.Headers["Authorization"].ToString();
        if (string.IsNullOrWhiteSpace(auth)) return Task.FromResult(AuthenticateResult.NoResult());

        if (auth.StartsWith("Bearer "))
        {
            var token = auth.Substring("Bearer ".Length).Trim();
            // If token looks like a JWT, try to read the sub/email/username claims from it.
            var claimsList = new System.Collections.Generic.List<Claim>();
            try
            {
                if (token.Contains('.'))
                {
                    var handler = new System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler();
                    var jwt = handler.ReadJwtToken(token);
                    var sub = jwt.Claims.FirstOrDefault(c => c.Type == System.IdentityModel.Tokens.Jwt.JwtRegisteredClaimNames.Sub)?.Value;
                    var email = jwt.Claims.FirstOrDefault(c => c.Type == System.IdentityModel.Tokens.Jwt.JwtRegisteredClaimNames.Email)?.Value;
                    var username = jwt.Claims.FirstOrDefault(c => c.Type == "username")?.Value;
                    if (!string.IsNullOrWhiteSpace(sub)) claimsList.Add(new Claim("sub", sub));
                    if (!string.IsNullOrWhiteSpace(email)) claimsList.Add(new Claim("email", email));
                    if (!string.IsNullOrWhiteSpace(username)) claimsList.Add(new Claim("username", username));
                }
                else
                {
                    // treat token as plain user id
                    claimsList.Add(new Claim("sub", token));
                }
            }
            catch
            {
                // fallback: treat token as raw sub
                claimsList.Add(new Claim("sub", token));
            }

            var claims = claimsList.ToArray();
            var identity = new ClaimsIdentity(claims, Scheme.Name);
            var principal = new ClaimsPrincipal(identity);
            var ticket = new AuthenticationTicket(principal, Scheme.Name);
            return Task.FromResult(AuthenticateResult.Success(ticket));
        }

        return Task.FromResult(AuthenticateResult.NoResult());
    }
}
